### ISSUE TITLE
Bugs in InputAxesDelta

### ISSUE THREAD

**Issue by ahickey** [StrikerX3/JXInput#15]
getDelta for LEFT_THUMBSTICK_X is returning the delta of getRXDelta()

public float getDelta(final XInputAxis axis) {
        switch (axis) {
            case LEFT_THUMBSTICK_X:
                return getRXDelta();

getRawDelta has the same bug

 public int getRawDelta(final XInputAxis axis) {
        switch (axis) {
            case LEFT_THUMBSTICK_X:
                return getRXRawDelta();

**Comment by StrikerX3** [comment]
Good catch. Fixing those right away.
