### ISSUE TITLE
Vibration works but poll() returns false 

### ISSUE THREAD

**Issue by pekuz** [StrikerX3/JXInput#16]
Hi Ivan,

I'm facing unexpected behaviour. My observation is that setting a vibration on a device makes it vibrate but polling the same device returns false / not connected.

My env is Win 7 64 bit with java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode).

  Any idea, please?
  Petr

PS: reading native 

if (mHandle != NULL)
{
	mGetState = (XInputGetStatePointer)GetProcAddress(mHandle, (LPCSTR)100); // Ordinal 100 is the same as XInputGetState but supports the Guide button.
	mSetState = (XInputSetStatePointer)GetProcAddress(mHandle, "XInputSetState");
	mLoaded = true;
}

suspecting that for (LPCSTR)100 it can return NULL and there should be a fallback to XInputGetState in that case, no? On my controller there is no guide button.

**Comment by pekuz** [comment]
I have changed to

if (mHandle != NULL)
{
	mGetState = (XInputGetStatePointer)GetProcAddress(mHandle, (LPCSTR)100); // Ordinal 100 is the same as XInputGetState but supports the Guide button.
        if (mGetState == NULL) {
               mGetState = (XInputGetStatePointer)GetProcAddress(mHandle, (LPCSTR)"XInputGetState");
         }
	mSetState = (XInputSetStatePointer)GetProcAddress(mHandle, "XInputSetState");
	mLoaded = true;
}

and it helped. So likely (LPCSTR)100 is optional.

  Hope it helps
  Petr

**Comment by StrikerX3** [comment]
(LPCSTR)100 is not optional. It points to the function that can read the Guide button state. But it seems that not all versions of the XInput library support that, so the fallback is a reasonable option in those cases.
