### ISSUE TITLE
Using File separator instead of path separator in NativeLibraryHelper.java 

### ISSUE THREAD

**Issue by ahickey** [StrikerX3/JXInput#17]
From NativeLibraryHelper.java
165	        final String pathSep = File.separator;
166	        System.setProperty("java.library.path",

File separator is \\
Path separator is ; 
(under Windows)

Should be 
165   final String pathSep = File.pathSeparator;

Found out the long way that after initializing JXInput libraries found on the last part of java.library.path could no longer be found!

**Comment by StrikerX3** [comment]
Latest push should fix this issue.
