### ISSUE TITLE
Eliminate dependency on  Visual C++ Redistributable Packages for Visual Studio 2015

### ISSUE THREAD

**Issue by pekuz** [StrikerX3/JXInput#20]
It showed up that  Visual C++ Redistributable Packages for Visual Studio 2015 is not that common. 

I wonder if it would not be possible to avoid dependency on  Visual C++ Redistributable Packages for Visual Studio.

**Comment by StrikerX3** [comment]
It is possible but not recommended when creating DLLs. See [this StackOverflow answer](http://stackoverflow.com/a/10636764).

Most games developed in C++ include the appropriate Microsoft Visual C++ Runtime Installer with their package, which is then automatically installed as part of the installation process. I don't think it's worth the risk of causing nasty errors for the convenience of not needing to install a package.

**Comment by pekuz** [comment]
OK
