### ISSUE TITLE
Add XInput Controller Guide Button

### ISSUE THREAD

**Issue by BlueMustache** [StrikerX3/JXInput#4]
Could you please add support for the XBOX guide button to your library.
The thing with the X on it, so I can pull up the pause menu in my game or whatever.

Here is some code.
https://github.com/DieKatzchen/GuideButtonPoller/blob/master/GuideButtonPoller.cpp

Here is a discussion.
http://forums.tigsource.com/index.php?topic=26792.0

I don't know C++. I only know Java.
Thanks!

**Comment by StrikerX3** [comment]
I will look into it. Seems like Microsoft hasn't exposed the Guide button constant in the XInput include file.

**Comment by BlueMustache** [comment]
Thanks for your prompt response. I hope the code snippet helps. Loo forwards to an update.

**Comment by StrikerX3** [comment]
Pushing an update to the library in a moment. My changes were ultimately based on code by Remi Gillig (see https://github.com/speps/XInputDotNet/blob/master/XInputInterface/GamePad.cpp), which was released under the MIT License.

**Comment by StrikerX3** [comment]
You will need to update the library dependency to version 0.5.

**Comment by BlueMustache** [comment]
Thanks for adding the changes!
