### ISSUE TITLE
Importing into Eclipse

### ISSUE THREAD

**Issue by mindinsomnia** [StrikerX3/JXInput#5]
Hey StrikerX3, this looks like exactly what I need, but at the risk of asking a very dumb question, how do I import this into Eclipse to use it? I tried importing it as an existing Maven project, then adding the imports to my source and just checking for support, but the application crashes immediately every time I try running it. 

I won't copy the entire log but here is the dump it gave me of the error:

A fatal error has been detected by the Java Runtime Environment:
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00f0f3e0, pid=7116, tid=6524

JRE version: Java(TM) SE Runtime Environment (8.0_45-b14) (build 1.8.0_45-b14)
Java VM: Java HotSpot(TM) Client VM (25.45-b02 mixed mode windows-x86 )
Problematic frame:
C  0x00f0f3e0

Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

If you would like to submit a bug report, please visit:
  http://bugreport.java.com/bugreport/crash.jsp
The crash happened outside the Java Virtual Machine in native code.
See problematic frame for where to report the bug.

---------------  T H R E A D  ---------------

Current thread (0x001ec800):  JavaThread "main" [_thread_in_native, id=6524, stack(0x00ec0000,0x00f10000)]

siginfo: ExceptionCode=0xc0000005, ExceptionInformation=0x00000008 0x00f0f3e0

Registers:
EAX=0x0000048f, EBX=0x1abda4e8, ECX=0x00000000, EDX=0x00000001
ESP=0x00f0f3b8, EBP=0x001ec940, ESI=0x0269c0c3, EDI=0x001ec800
EIP=0x00f0f3e0, EFLAGS=0x00210206

Top of Stack: (sp=0x00f0f3b8)
0x00f0f3b8:   00f0f3b8 1abda4e8 00f0f3ec 191eff68
0x00f0f3c8:   00000000 1abda4e8 00000000 00f0f3e8
0x00f0f3d8:   00f0f414 02694040 04813ec8 02698a99
0x00f0f3e8:   04846a98 00000000 04846a70 00f0f3f4
0x00f0f3f8:   1abae9f9 00f0f450 1abd9e18 00000000
0x00f0f408:   1abaecd8 00f0f3e8 00f0f450 00f0f474
0x00f0f418:   02693e60 00000000 00000000 00000000
0x00f0f428:   00000000 00000000 00000000 00000000 

Instructions: (pc=0x00f0f3e0)
0x00f0f3c0:   ec f3 f0 00 68 ff 1e 19 00 00 00 00 e8 a4 bd 1a
0x00f0f3d0:   00 00 00 00 e8 f3 f0 00 14 f4 f0 00 40 40 69 02
0x00f0f3e0:   c8 3e 81 04 99 8a 69 02 98 6a 84 04 00 00 00 00
0x00f0f3f0:   70 6a 84 04 f4 f3 f0 00 f9 e9 ba 1a 50 f4 f0 00 

Register to memory mapping:

EAX=0x0000048f is an unknown value
EBX={method} {0x1abda4ec} 'pollDevice' '(ILjava/nio/ByteBuffer;)I' in 'com/ivan/xinput/natives/XInputNatives'
ECX=0x00000000 is an unknown value
EDX=0x00000001 is an unknown value
ESP=0x00f0f3b8 is pointing into the stack for thread: 0x001ec800
EBP=0x001ec940 is an unknown value
ESI=0x0269c0c3 is at code_begin+627 in an Interpreter codelet
method entry point (kind = native)  [0x0269be50, 0x0269c3f0]  1440 bytes
EDI=0x001ec800 is a thread

Stack: [0x00ec0000,0x00f10000],  sp=0x00f0f3b8,  free space=316k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x00f0f3e0

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.ivan.xinput.natives.XInputNatives.pollDevice(ILjava/nio/ByteBuffer;)I+0
j  com.ivan.xinput.XInputDevice.poll()Z+9
j  com.ivan.xinput.XInputDevice.<init>(I)V+82
j  com.ivan.xinput.XInputDevice.<clinit>()V+23
v  ~StubRoutines::call_stub
j  obsessiondemo.Demo3DGraphics.start()V+182
j  Obsession.Obsession.run()V+540
j  java.lang.Thread.run()V+11
j  Obsession.Obsession.<init>(Ljava/lang/String;IILObsession/State;)V+363
j  obsessiondemo.ObsessionDemo.<init>()V+16
j  obsessiondemo.ObsessionDemo.main([Ljava/lang/String;)V+3
v  ~StubRoutines::call_stub

Again at the risk of sounding stupid, since I'm sure I'm just missing something simple, do you have any ideas what I might be doing wrong?

**Comment by StrikerX3** [comment]
It doesn't look like you're doing anything wrong there.

I suspect there is a buffer overrun happening in the `XInputNatives.pollDevice()` method; the buffer allocated in Java for the `XINPUT_STATE` struct might not be large enough. If that's the case, then increasing the buffer size in [line 70 of XInputDevice.java](https://github.com/StrikerX3/JXInput/blob/master/XInputDevice_Java/src/main/java/com/ivan/xinput/XInputDevice.java#L70) to 20 should fix the issue.
But then, I might be wrong there. I just printed out `sizeof(XINPUT_STATE)` and it returns `16` for both 32- and 64-bit platforms.
Try running the JVM with the `-XX:+CreateMinidumpOnCrash` VM argument. When it crashes, it should generate a largeish `hs_err_pid####.mdmp` along with a corresponding `hs_err_pid####.log` file in the project folder. Send me both files. The `mdmp` should compress nicely.

Another thing you can try is to compile the Native project according to the platform you're using (Release|x64 for 64-bit, for example) and copying the resulting DLLs into the appropriate folder of the Java project (`src/main/resources/lib/native/win-x##`), then `mvn clean install` to make sure you get the updated DLLs in your project. [Visual Studio 2015 Community Edition](https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs.aspx) works and is free.

**Comment by mindinsomnia** [comment]
Hey StrikerX3! Thanks for the response! Sure thing. OK I just started completely fresh, unzipped the zip into my Eclipse workspace, went to File, Import, Maven, Existing Project, Eclipse has found the "pom.xml" file, which imported a project called "xinput-device". After that I've gone to my project's properties, Java Build Path, and I've added xinput-device to my current project.

After that I've just gone to my main application and added to the start of it:

// check if XInput 1.3 is available
if (XInputDevice.isAvailable()) {
    System.out.println("XInput 1.3 is available on this platform.");
}

// check if XInput 1.4 is available
if (XInputDevice14.isAvailable()) {
    System.out.println("XInput 1.4 is available on this platform.");
}

I've added the imports as well to the top of the java file. I've added the -XX:+CreateMinidumpOnCrash argument to the VM and it's spat the error log and crashed with the same error as before.

Ouch, jeez, 300MB, I see now why you suggesting compressing it!

Here's a download link to the log:
https://dl.dropboxusercontent.com/u/1621976/hs_err_pid6740.zip

When I get home tonight I'll try compiling the native project like you suggest. Thankyou very much for the help StrikerX3, greatly appreciated!

**Comment by StrikerX3** [comment]
Huh, strangely enough, the log and dump file tells me your code never actually touched the native library. It crashed on the boundary between Java and native code for some reason. Unfortunately I can't tell what exactly happened because there are no debug symbols for the JVM.

Try downloading the latest JDK from [here](http://www.oracle.com/technetwork/java/javase/downloads/index.html) and see if that helps.

**Comment by mindinsomnia** [comment]
Ah you're wonderful! Thankyou StrikerX3! I just tried on my laptop, downloaded the latest JDK, set it up and it worked flawlessly, I had a controller vibrate across my desk to celebrate, thankyou very much! I assume that was the problem my other computer had too, so I'll be sure to do the same when I get back home.

And thankyou for this wonderful library! Can't wait to use it in my next project.

**Comment by StrikerX3** [comment]
Awesome! Glad I could help.
